# Generated by Django 5.1.1 on 2024-12-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registros',
            fields=[
                ('idregistro', models.IntegerField(primary_key=True, serialize=False)),
                ('oqfoifeito', models.TextField(max_length=255)),
            ],
        ),
    ]
