# Generated by Django 5.1.1 on 2024-12-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_calendario', '0002_registros_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registros',
            name='oqfoifeito',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
