# Generated by Django 5.1.1 on 2024-12-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_calendario', '0003_alter_registros_oqfoifeito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registros',
            name='oqfoifeito',
            field=models.TextField(max_length=255),
        ),
    ]
